// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Node = {
    node_type: string;
    backend_type: string;
    workers: (number | null);
    status: string;
    redis_url?: (string | null);
    sqlite_file?: (string | null);
};

export type Task = {
    id: string;
    name: string;
    description: string;
    status: TaskStatus;
    retries?: number;
    expires_at?: (string | null);
    scheduled_at?: (string | null);
    started_at?: (string | null);
    completed_at?: (string | null);
};

export type TaskCreate = {
    name: string;
    description: string;
};

export type TaskDelete = {
    id: string;
    name: string;
    description: string;
    status: TaskStatus;
    retries?: number;
    expires_at?: (string | null);
    scheduled_at?: (string | null);
    started_at?: (string | null);
    completed_at?: (string | null);
};

/**
 * Task status enumeration.
 */
export type TaskStatus = 'pending' | 'scheduled' | 'periodic' | 'running' | 'completed' | 'failed';

export type TaskUpdate = {
    name: string;
    description: string;
};

export type User = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ServeSpaAppRootResponse = (unknown);

export type ServeSpaAppData = {
    path: string;
};

export type ServeSpaAppResponse = (unknown);

export type LoginTestAuthResponse = (User);

export type NodesGetCurrentNodeResponse = (Node);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (Task);

export type TasksGetTasksData = {
    limit?: number;
    page?: number;
};

export type TasksGetTasksResponse = (Array<Task>);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (Task);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (TaskDelete);

export type TasksGetMetricsResponse = (unknown);

export type TasksTriggerPingResponse = (Task);

export type UsersReadUserMeResponse = (User);